# 
# Vagrantfile per un singolo nodo (dev, developer) 
# per la compilazione dei progetti, 
# con Oracle, Java e Maven. 
# 

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # Configurazioni comuni.

    # Ubuntu 16.04 LTS 64 bit VirtualBox (Bento)
    config.vm.box = "bento/ubuntu-16.04"
    # config.vm.box_url = "https://app.vagrantup.com/bento/boxes/ubuntu-16.04"

    # folder per le risorse condivise per gli ambienti Asw (/home/asw/_shared/resources e /home/asw/_shared/scripts) 
    config.vm.synced_folder "../_shared/", "/home/asw/_shared", :mount_options => ["dmode=777", "fmode=777"]

    #
    # Configurazione del nodo "server", che prevede: 
    # - Oracle Java SDK 8 
    #
    config.vm.define "server" do |node|
        node.vm.hostname = "server"    
        
        node.vm.provider "virtualbox" do |v| 
			v.memory = 1536 
			v.cpus = 1
        end 

        node.vm.network "forwarded_port", guest: 22, host: 2222, id: 'ssh', auto_correct: true 
        node.ssh.forward_agent = true

        node.vm.network :private_network, ip: "10.11.1.151", virtualbox__intnet: true

        node.vm.network "forwarded_port", guest: 8080, host: 8088, id: 'http', auto_correct: true

        # provisioning con bash 
        node.vm.provision :shell, :inline => 'apt-get update'
        node.vm.provision :shell, :inline => 'apt-get install -y maven'
        
        node.vm.provision :shell, path: "../_shared/scripts/setup-java.sh"
        #node.vm.provision :shell, path: "../_shared/scripts/setup-gradle.sh"
        node.vm.provision :shell, path: "../_shared/scripts/setup-wildfly.sh"
        node.vm.provision :shell, path: "../_shared/scripts/service/start-wildfly-service.sh"

        node.vm.provision :shell, :inline => "echo '10.11.1.151 server' >> /etc/hosts"
        node.vm.provision :shell, :inline => "echo '10.11.1.251 client' >> /etc/hosts"

        node.vm.provision "up", type: "shell", run: "always", inline: 'bash /vagrant/provision_up.sh &' 
		
        node.vm.provision :shell, 
            inline: "echo  'configurazione nodo server completata'"

    end

    #
    # Configurazione del nodo "client", che prevede: 
    # - Oracle Java SDK 8 
    #
    config.vm.define "client" do |node|
        node.vm.hostname = "client"    
        
        node.vm.provider "virtualbox" do |v| 
			v.memory = 1536 
			v.cpus = 1
        end 

        node.vm.network "forwarded_port", guest: 22, host: 2222, id: 'ssh', auto_correct: true 
        node.ssh.forward_agent = true

        node.vm.network :private_network, ip: "10.11.1.251", virtualbox__intnet: true

        # provisioning con bash 
        node.vm.provision :shell, :inline => 'apt-get update'
        node.vm.provision :shell, :inline => 'apt-get install -y maven'

        node.vm.provision :shell, path: "../_shared/scripts/setup-java.sh"

        node.vm.provision :shell, :inline => "echo '10.11.1.151 server' >> /etc/hosts"
        node.vm.provision :shell, :inline => "echo '10.11.1.251 client' >> /etc/hosts"

        node.vm.provision "up", type: "shell", run: "always", inline: 'bash /vagrant/provision_up.sh &' 
		
        node.vm.provision :shell, 
            inline: "echo  'configurazione nodo client completata'"

    end

end
